const animals = [
    {
        id: 1,
        name: "Bison",
        image: "images/animals/primary/bison.png",
        rarity: "rare",
        yield: 2000,
        collect: 0,
    },
    {
        id: 2,
        name: "Pig",
        image: "images/animals/primary/pig.png",
        rarity: "common",
        yield: 500,
        collect: 0,
    },
    {
        id: 3,
        name: "Cow",
        image: "images/animals/primary/cow.png",
        rarity: "common",
        yield: 500,
        collect: 0,
    },
    {
        id: 4,
        name: "Camel",
        image: "images/animals/primary/camel.png",
        rarity: "common",
        yield: 500,
        collect: 0,
    },
    {
        id: 5,
        name: "Deer",
        image: "images/animals/primary/deer.png",
        rarity: "uncommon",
        yield: 1000,
        collect: 0,
    },
    {
        id: 6,
        name: "Dino",
        image: "images/animals/primary/dino.png",
        rarity: "super-rare",
        yield: 5000,
        collect: 0,
    },
    {
        id: 7,
        name: "Elephant",
        image: "images/animals/primary/elephant.png",
        rarity: "uncommon",
        yield: 1000,
        collect: 0,
    },
    {
        id: 8,
        name: "Elk",
        image: "images/animals/primary/elk.png",
        rarity: "rare",
        yield: 2000,
        collect: 0,
    },
    {
        id: 9,
        name: "Fox",
        image: "images/animals/primary/fox.png",
        rarity: "uncommon",
        yield: 1000,
        collect: 0,
    },
    {
        id: 10,
        name: "Goat",
        image: "images/animals/primary/goat.png",
        rarity: "common",
        yield: 500,
        collect: 0,
    },
    {
        id: 11,
        name: "Gorilla",
        image: "images/animals/primary/gorilla.png",
        rarity: "super-rare",
        yield: 5000,
        collect: 0,
    },
    {
        id: 12,
        name: "Giraffe",
        image: "images/animals/primary/giraffe.png",
        rarity: "rare",
        yield: 2000,
        collect: 0,
    },
    {
        id: 13,
        name: "Lion",
        image: "images/animals/primary/lion.png",
        rarity: "rare",
        yield: 2000,
        collect: 0,
    },
    {
        id: 14,
        name: "Big Bear",
        image: "images/animals/primary/big-bear.png",
        rarity: "super-rare",
        yield: 5000,
        collect: 0,
    },
    {
        id: 15,
        name: "Panda",
        image: "images/animals/primary/panda.png",
        rarity: "uncommon",
        yield: 1000,
        collect: 0,
    },
    {
        id: 16,
        name: "Penguin",
        image: "images/animals/primary/penguin.png",
        rarity: "rare",
        yield: 500,
        collect: 0,
    },
    {
        id: 17,
        name: "Panther",
        image: "images/animals/primary/panther.png",
        rarity: "super-rare",
        yield: 5000,
        collect: 0,
    },
    {
        id: 18,
        name: "Rare Elephant",
        image: "images/animals/primary/rare-elephant.png",
        rarity: "super-rare",
        yield: 5000,
        collect: 0,
    },
    {
        id: 19,
        name: "Zebra",
        image: "images/animals/primary/zebra.png",
        rarity: "uncommon",
        yield: 1000,
        collect: 0,
    },
    {
        id: 20,
        name: "Sheep",
        image: "images/animals/primary/sheep.png",
        rarity: "common",
        yield: 500,
        collect: 0,
    },
    {
        id: 21,
        name: "Rhino",
        image: "images/animals/primary/rhino.png",
        rarity: "rare",
        yield: 2000,
        collect: 0,
    },
    {
        id: 22,
        name: "Tiger",
        image: "images/animals/primary/tiger.png",
        rarity: "rare",
        yield: 2000,
        collect: 0,
    },
    {
        id: 23,
        name: "Wolverine",
        image: "images/animals/primary/wolverine.png",
        rarity: "super-rare",
        yield: 5000,
        collect: 0,
    },
    {
        id: 24,
        name: "Yak",
        image: "images/animals/primary/yak.png",
        rarity: "uncommon",
        yield: 1000,
        collect: 0,
    },
    {
        id: 25,
        name: "Hedgehog",
        image: "images/animals/primary/hedgehog.png",
        rarity: "common",
        yield: 500,
        collect: 0,
    },
    {
        id: 26,
        name: "Hippo",
        image: "images/animals/primary/hippo.png",
        rarity: "rare",
        yield: 2000,
        collect: 0,
    },
    //todo: add more animals
    // {
    //     id: 27,
    //     name: "Horse",
    //     image: "images/animals/primary/horse.png",
    //     rarity: "common",
    //     yield: 500,
    //     collect: 0,
    // },
    // {
    //     id: 28,
    //     name: "Kangaroo",
    //     image: "images/animals/primary/kangaroo.png",
    //     rarity: "uncommon",
    //     yield: 1000,
    //     collect: 0,
    // },
    // {
    //     id: 29,
    //     name: "Koala",
    //     image: "images/animals/primary/koala.png",
    //     rarity: "uncommon",
    //     yield: 1000,
    //     collect: 0,
    // },
    // {
    //     id: 30,
    //     name: "Leopard",
    //     image: "images/animals/primary/leopard.png",
    //     rarity: "rare",
    //     yield: 2000,
    //     collect: 0,
    // },
    // {
    //     id: 31,
    //     name: "Llama",
    //     image: "images/animals/primary/llama.png",
    //     rarity: "common",
    //     yield: 500,
    //     collect: 0,
    // },
    // {
    //     id: 32,
    //     name: "Monkey",
    //     image: "images/animals/primary/monkey.png",
    //     rarity: "uncommon",
    //     yield: 1000,
    //     collect: 0,
    // },
    // {
    //     id: 33,
    //     name: "Moose",
    //     image: "images/animals/primary/moose.png",
    //     rarity: "rare",
    //     yield: 2000,
    //     collect: 0,
    // },
    // {
    //     id: 34,
    //     name: "Mouse",
    //     image: "images/animals/primary/mouse.png",
    //     rarity: "common",
    //     yield: 500,
    //     collect: 0,
    // },
    // {
    //     id: 35,
    //     name: "Pig",
    //     image: "images/animals/primary/pig.png",
    //     rarity: "common",
    //     yield: 500,
    //     collect: 0,
    // },
    // {
    //     id: 36,
    //     name: "Polar Bear",
    //     image: "images/animals/primary/polar-bear.png",
    //     rarity: "super-rare",
    //     yield: 5000,
    //     collect: 0,
    // },
    // {
    //     id: 37,
    //     name: "Rabbit",
    //     image: "images/animals/primary/rabbit.png",
    //     rarity: "common",
    //     yield: 500,
    //     collect: 0,
    // },
    // {
    //     id: 38,
    //     name: "Raccoon",
    //     image: "images/animals/primary/raccoon.png",
    //     rarity: "uncommon",
    //     yield: 1000,
    //     collect: 0,
    // },
    // {
    //     id: 39,
    //     name: "Sloth",
    //     image: "images/animals/primary/sloth.png",
    //     rarity: "uncommon",
    //     yield: 1000,
    //     collect: 0,
    // },
    // {
    //     id: 40,
    //     name: "Squirrel",
    //     image: "images/animals/primary/squirrel.png",
    //     rarity: "common",
    //     yield: 500,
    //     collect: 0,
    // },
    // {
    //     id: 41,
    //     name: "Turtle",
    //     image: "images/animals/primary/turtle.png",
    //     rarity: "common",
    //     yield: 500,
    //     collect: 0,
    // },
    // {
    //     id: 42,
    //     name: "Wolf",
    //     image: "images/animals/primary/wolf.png",
    //     rarity: "rare",
    //     yield: 2000,
    //     collect: 0,
    // }
];



export const useAnimals = () => {
    return animals.slice();
}
